### ISSUE TITLE
BUG-149 Bestiary: printer view not working

### ISSUE THREAD

**Issue by crawltracker** [Pf2eToolsOrg/Pf2eTools#121]
Steps to reproduce
1) Open bestiary.
2) Add "Adult Black Dragon" and "Adult Blue Dragon" with the plus button to the list.
3) Press "Printer view" button.
4) Observe as nothing happens.

Severity
High

Additional information
Browser: Google Chrome (v 104.0.5112.81)
Extensions: tested after disabling all extensions and deleting cookie data

The following error is logged into console:

utils-list.js:1 Uncaught (in promise) TypeError: ListUtil.getSublisted is not a function
    at Object.genericPinKeyMapper (utils-list.js:1:21577)
    at PrintModeView.popTblGetNumShown (bestiary.js:17:5689)
    at PrintModeView._renderContent (shared.js:70:29839)
    at PrintModeView.pOpen (shared.js:75:104)
    at PrintModeView.pHandleSub (shared.js:75:805)
    at BestiaryPage.pDoLoadSubHash (bestiary.js:17:590)

- solonkovda#6481
Verification: 0

**Comment by crawltracker** [comment]
Note - MrVauxs#8622

Resolved - Report closed.
