### ISSUE TITLE
BUG-123 Quick Reference page loading forever

### ISSUE THREAD

**Issue by crawltracker** [Pf2eToolsOrg/Pf2eTools#93]
Steps to reproduce
go to quick reference page on pf2e

Severity
High

Additional information
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.getEntryIdLookup (shared.js:160:17908)
    at Object.showBookContent (bookutils.js:1:6248)
    at doPopulate (bookutils.js:1:19683)
    at Object.pLoadBook (bookutils.js:1:19964)
    at async pHandleFound (bookutils.js:1:16768)

- Coul#3188
Verification: 0

**Comment by crawltracker** [comment]
Note - MrVauxs#8622

Side-effect of Paizo Compliancy update. Will be fixed sometime soon.

**Comment by crawltracker** [comment]
Note - MrVauxs#8622

Resolved - Report closed.
